application: test
version: 1
runtime: go
api_version: go1

handlers:
  - url: /api/v1/.*
    script: _go_app
  - url: /static
    static_dir: client/build
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html

skip_files:
  - ^(.*/)?.*webapp/.*$
  - ^(webapp/.*)
